name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Cache Flutter dependencies
      uses: action/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'dev' or 'beta'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ecommers
    - name: Build Android app
      run: flutter build apk --target-platform android-arm
      working-directory: ecommers
